services:
  teeproxy:
    build:
      context: .
    ports:
      - "8000:8000"
    command: /teeproxy -l=:8000 -a="null-server-1:5000" -b="null-server-2:5000" -debug=false

networks:
  default:
    external:
      name: experiment
